platform :ios, '8.0'
use_frameworks!
target ‘个人简历’ do
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.2'
pod 'SDCycleScrollView', '~> 1.65'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJRefresh', '~> 3.1.10'
pod 'Masonry', '~> 1.0.1'
pod 'AMapLocation-NO-IDFA'
pod 'AMapSearch-NO-IDFA'
pod 'RongCloudIM/IMKit', '~> 2.8.9'
pod 'RongCloudIM/IMLib', '~> 2.8.9'
pod 'WechatOpenSDK', '~> 1.7.7’ 
end
